name: kisan_sevak
description: AI-powered smart agriculture assistant for Indian farmers
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # UI & Animation
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  flutter_svg: ^2.0.9
  lottie: ^3.0.0
  shimmer: ^3.0.0
  
  # State Management
  provider: ^6.1.1
  flutter_riverpod: ^2.4.9
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  
  # Location & Maps
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  
  # Camera & Image
  camera: ^0.10.5+9
  image_picker: ^1.0.7
  image_cropper: ^5.0.1
  
  # Localization
  easy_localization: ^3.0.3
  intl: ^0.19.0
  
  # Storage
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  
  # Network & API
  http: ^1.1.2
  dio: ^5.4.0
  
  # Utils
  uuid: ^4.2.2
  logger: ^2.0.2+1
  url_launcher: ^6.2.2
  package_info_plus: ^5.0.1
  device_info_plus: ^9.1.1
  connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/translations/
    
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Mukta
      fonts:
        - asset: assets/fonts/Mukta-Regular.ttf
        - asset: assets/fonts/Mukta-Medium.ttf
          weight: 500
        - asset: assets/fonts/Mukta-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Mukta-Bold.ttf
          weight: 700
